### ISSUE TITLE
Xcode 9.2 complaining about conflicting code signing settings when automatic signing is selected

### ISSUE THREAD

**Issue by zsombornagy** [agens-no/iMessageStickerUnity#25]
Hi!

Xcode 9.2 is complaining about conflicting code signing settings when automatic signing is selected.

I found that removing the CODE_SIGN_IDENTITY entries solves the problem in this case.

I made it work for myself by changing this in PBXProject.cs:

```
            config.AddProperty("CODE_SIGN_IDENTITY[sdk=iphoneos*]", "iPhone Distribution");
```

to only add it if automatic signing is selected:

```
            if (!automaticSigning)
            {
                config.AddProperty("CODE_SIGN_IDENTITY[sdk=iphoneos*]", "iPhone Distribution");
            }
```

But I thought I would report it anyway.

Thanks for the great plugin!

**Comment by skjalgsm** [comment]
please submit a PR with these changes :)

**Comment by zsombornagy** [comment]
I don't know how to do that, but I'll try! (now I'm just pressing buttons accidentally, sorry)

**Comment by skjalgsm** [comment]
I fixed it then :)

**Comment by zsombornagy** [comment]
Great, thanks! :)

Sorry, I didn't have time to figure out how PRs work :(

**Comment by skjalgsm** [comment]
No problem :)

**Comment by zsombornagy** [comment]
Hi! I just checked your latest release, and I still have the problem.

Shouldn't we check for the oppositve, so if it's NOT automatic signing?
